version: "3.9"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - HTTP_PORT=8080
      - JWT_SECRET=dev-secret
      - POSTGRES_DSN=postgres://postgres:postgres@postgres:5432/otpapp?sslmode=disable
      - REDIS_ADDR=redis:6379
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=otpapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  pgdata:


